export default function printLedger(person, transactions) {

    const rows = transactions.map((transaction) => `

        <tr>

            <td>${new Date(
                transaction.transaction_date
            ).toLocaleDateString()}</td>

            <td>${transaction.transaction_type}</td>

            <td>₹${transaction.amount}</td>

            <td>${transaction.note || "-"}</td>

        </tr>

    `).join("");

    const printWindow = window.open("", "_blank");

    printWindow.document.write(`

<!DOCTYPE html>

<html>

<head>

<title>${person.name} Ledger</title>

<style>

body{

    font-family:Arial,sans-serif;

    margin:40px;

    color:#222;

}

h1{

    color:#2563eb;

}

table{

    width:100%;

    border-collapse:collapse;

    margin-top:25px;

}

th,td{

    border:1px solid #ddd;

    padding:10px;

    text-align:left;

}

th{

    background:#2563eb;

    color:white;

}

.info{

    margin-top:20px;

    line-height:1.8;

}

.balance{

    font-size:22px;

    font-weight:bold;

    color:#2563eb;

    margin-top:20px;

}

.footer{

    margin-top:40px;

    text-align:center;

    color:#777;

    font-size:12px;

}

</style>

</head>

<body>

<h1>DebtBook</h1>

<h2>Person Ledger</h2>

<div class="info">

<strong>Name :</strong> ${person.name}<br>

<strong>Phone :</strong> ${person.phone}<br>

<strong>Email :</strong> ${person.email}<br>

</div>

<div class="balance">

Current Balance :
₹${Number(person.balance).toLocaleString()}

</div>

<table>

<thead>

<tr>

<th>Date</th>

<th>Type</th>

<th>Amount</th>

<th>Note</th>

</tr>

</thead>

<tbody>

${rows}

</tbody>

</table>

<div class="footer">

Generated by DebtBook

</div>

<script>

window.onload=function(){

window.print();

window.close();

}

</script>

</body>

</html>

`);

    printWindow.document.close();

}
